[package]
name = "wyv"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.24"
tui = "0.18"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
seahash = "4.1"